// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered sub-task generator for complex tasks.
 *
 * - generateSubtasks - Generates sub-tasks for a given complex task.
 * - GenerateSubtasksInput - The input type for the generateSubtasks function.
 * - GenerateSubtasksOutput - The return type for the generateSubtasks function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSubtasksInputSchema = z.object({
  taskDescription: z.string().describe('The description of the complex task.'),
});
export type GenerateSubtasksInput = z.infer<typeof GenerateSubtasksInputSchema>;

const GenerateSubtasksOutputSchema = z.object({
  subtasks: z.array(z.string()).describe('An array of sub-tasks for the given task.'),
});
export type GenerateSubtasksOutput = z.infer<typeof GenerateSubtasksOutputSchema>;

export async function generateSubtasks(input: GenerateSubtasksInput): Promise<GenerateSubtasksOutput> {
  return generateSubtasksFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSubtasksPrompt',
  input: {schema: GenerateSubtasksInputSchema},
  output: {schema: GenerateSubtasksOutputSchema},
  prompt: `You are a helpful assistant that breaks down complex tasks into smaller, manageable sub-tasks.

  Given the following task description, generate a list of sub-tasks that need to be completed to accomplish the main task.
  The sub-tasks should be clear and actionable.

  Task Description: {{{taskDescription}}}

  Return the subtasks as a JSON array of strings.
  `,
});

const generateSubtasksFlow = ai.defineFlow(
  {
    name: 'generateSubtasksFlow',
    inputSchema: GenerateSubtasksInputSchema,
    outputSchema: GenerateSubtasksOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
